services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.14
    command:
      - etcd
      - --listen-client-urls
      - http://0.0.0.0:2379
      - --advertise-client-urls
      - http://0.0.0.0:2380

  pebble:
    image: ghcr.io/letsencrypt/pebble:2.8.0
    command:
      - --dnsserver
      - host.docker.internal:5053
    environment:
      PEBBLE_VA_NOSLEEP: 1
      PEBBLE_WFE_NONCEREJECT: 0

  lb:
    image: nginx:alpine
    ports:
      - "5002:5002"
      - "5001:5001"
    volumes:
      - ./thundering_herd_lb.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
